In [8]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np
#create an array using numpy
#creating an 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1,type(arr1))
print(arr1.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
(5,)


In [10]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(1,6) #1 row and 5 columns

array([[1, 2, 3, 4, 5, 6]])

In [11]:
#2D array
arr2 = np.array([[1,2,3,4,5,6],[2,3,4,7,8,9]])
print(arr2)
arr2.shape

[[1 2 3 4 5 6]
 [2 3 4 7 8 9]]


(2, 6)

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.eye(3) #identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#attributes
arr = np.array([[1,2,3],[4,5,6]])

print("array:\n",arr)
print(type(arr))
print("no of dimensions:",arr.ndim)
print("size(no.of elements):",arr.size)
print("data type:",arr.dtype)
print("item size(in bytes):",arr.itemsize)

array:
 [[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
no of dimensions: 2
size(no.of elements): 6
data type: int64
item size(in bytes): 8


In [16]:
###numpy vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
#elements wise:-
print("Addition:",arr1+arr2)
print("substraction:",arr1-arr2)

Addition: [11 22 33 44 55]
substraction: [ -9 -18 -27 -36 -45]


In [17]:
#universal function
arr=np.array([1,2,3,4,5])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [18]:
#indexing and slicing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(arr[1:,2:])
print(arr[0:2,2:])
print(arr[0:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
[[3 4]
 [7 8]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [19]:
#modify the element
arr[0,0]= 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [20]:
arr[0:,0:2]= 100
print(arr)

[[100 100   3   4]
 [100 100   7   8]
 [100 100  11  12]]


In [21]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [22]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("series:\n",series)
print(type(series))

series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


In [23]:
data = {'a':1,'b':2,'c':3}
print(pd.Series(data))

a    1
b    2
c    3
dtype: int64


In [24]:
data = [10,20,30]
index = ['a','b','c']
print(pd.Series(data, index=index))

a    10
b    20
c    30
dtype: int64


In [25]:
#dataframe
data = {
    'Name':['Jack','John','Elle'],
    'Age':[30,29,27],
    'City':['Bangalore','Hyderabad','Mumbai']
}
df = pd.DataFrame(data)
print(pd.DataFrame(data))
np.array(df)

   Name  Age       City
0  Jack   30  Bangalore
1  John   29  Hyderabad
2  Elle   27     Mumbai


array([['Jack', 30, 'Bangalore'],
       ['John', 29, 'Hyderabad'],
       ['Elle', 27, 'Mumbai']], dtype=object)

In [26]:
df.loc[1]

Name         John
Age            29
City    Hyderabad
Name: 1, dtype: object

In [27]:
df['Name']

0    Jack
1    John
2    Elle
Name: Name, dtype: object

In [28]:
df.iloc[0][0]

C:\Users\amitj\AppData\Local\Temp\ipykernel_8000\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]


'Jack'

In [29]:
df

Name  Age       City
0  Jack   30  Bangalore
1  John   29  Hyderabad
2  Elle   27     Mumbai

In [30]:
df.at[1,'Age']

np.int64(29)

In [31]:
df.iat[1,2]

'Hyderabad'

In [32]:
#adding a column
df['Salary']=[50000,20000, 60000 ]

In [33]:
df

Name  Age       City  Salary
0  Jack   30  Bangalore   50000
1  John   29  Hyderabad   20000
2  Elle   27     Mumbai   60000

In [34]:
df.drop('Salary',axis=1)

Name  Age       City
0  Jack   30  Bangalore
1  John   29  Hyderabad
2  Elle   27     Mumbai

In [35]:
df

Name  Age       City  Salary
0  Jack   30  Bangalore   50000
1  John   29  Hyderabad   20000
2  Elle   27     Mumbai   60000

In [36]:
df.drop('Salary',axis=1,inplace=True)

In [37]:
df

Name  Age       City
0  Jack   30  Bangalore
1  John   29  Hyderabad
2  Elle   27     Mumbai

In [38]:
df['Age']=df['Age']+1
df

Name  Age       City
0  Jack   31  Bangalore
1  John   30  Hyderabad
2  Elle   28     Mumbai

In [39]:
print(df)
print("Shape:", df.shape)
print("Columns:", df.columns)


   Name  Age       City
0  Jack   31  Bangalore
1  John   30  Hyderabad
2  Elle   28     Mumbai
Shape: (3, 3)
Columns: Index(['Name', 'Age', 'City'], dtype='object')


In [40]:
%pip install pandas
import pandas as pd

Note: you may need to restart the kernel to use updated packages.


In [41]:
df =pd.read_csv('sales_data.csv')
df.head(5)

Date     Product Region Salesperson  Units Sold  Unit Price  \
0  2025-01-05      Laptop  North       Alice           3       750.0   
1  2025-01-10  Smartphone  South         Bob           5       500.0   
2  2025-02-02      Tablet   East     Charlie           2       300.0   
3  2025-02-14     Monitor   West       Diana           4       200.0   
4  2025-03-01  Headphones  North       Ethan          10       100.0   

   Total Sales  
0       2250.0  
1       2500.0  
2        600.0  
3        800.0  
4       1000.0

In [42]:
df.tail(5)

Date     Product Region Salesperson  Units Sold  Unit Price  \
5  2025-03-18      Laptop   East       Alice           1       800.0   
6  2025-04-04  Smartphone   West         Bob           6       550.0   
7  2025-04-20      Tablet  South     Charlie           3       280.0   
8  2025-05-09     Monitor  North       Diana           2       220.0   
9  2025-06-15  Headphones   East       Ethan           7        90.0   

   Total Sales  
5        800.0  
6       3300.0  
7        840.0  
8        440.0  
9        630.0

In [43]:
data

{'Name': ['Jack', 'John', 'Elle'],
 'Age': [30, 29, 27],
 'City': ['Bangalore', 'Hyderabad', 'Mumbai']}

In [44]:
df

Date     Product Region Salesperson  Units Sold  Unit Price  \
0  2025-01-05      Laptop  North       Alice           3       750.0   
1  2025-01-10  Smartphone  South         Bob           5       500.0   
2  2025-02-02      Tablet   East     Charlie           2       300.0   
3  2025-02-14     Monitor   West       Diana           4       200.0   
4  2025-03-01  Headphones  North       Ethan          10       100.0   
5  2025-03-18      Laptop   East       Alice           1       800.0   
6  2025-04-04  Smartphone   West         Bob           6       550.0   
7  2025-04-20      Tablet  South     Charlie           3       280.0   
8  2025-05-09     Monitor  North       Diana           2       220.0   
9  2025-06-15  Headphones   East       Ethan           7        90.0   

   Total Sales  
0       2250.0  
1       2500.0  
2        600.0  
3        800.0  
4       1000.0  
5        800.0  
6       3300.0  
7        840.0  
8        440.0  
9        630.0

In [45]:
#display the data types of each column
print("data types:\n",df.dtypes)

data types:
 Date            object
Product         object
Region          object
Salesperson     object
Units Sold       int64
Unit Price     float64
Total Sales    float64
dtype: object


In [46]:
#describe the dataframe
print("Statistical Summary:\n",df.describe())

Statistical Summary:
        Units Sold  Unit Price  Total Sales
count   10.000000   10.000000    10.000000
mean     4.300000  379.000000  1316.000000
std      2.750757  256.794341   989.951738
min      1.000000   90.000000   440.000000
25%      2.250000  205.000000   672.500000
50%      3.500000  290.000000   820.000000
75%      5.750000  537.500000  1937.500000
max     10.000000  800.000000  3300.000000


In [50]:
#handling missing values
df1 = pd.read_csv('data.csv')

In [51]:
print(df1.head(5))

         Date     Product Region Salesperson  Units Sold  Unit Price  \
0  2025-01-05      Laptop  North       Alice         3.0       750.0   
1  2025-01-10  Smartphone  South         Bob         5.0       500.0   
2  2025-02-02      Tablet    NaN     Charlie         2.0       300.0   
3  2025-02-14     Monitor   West         NaN         4.0       200.0   
4  2025-03-01  Headphones  North       Ethan         NaN       100.0   

   Total Sales  
0       2250.0  
1       2500.0  
2        600.0  
3        800.0  
4          NaN  


In [52]:
print(df.tail(5))

          Date     Product Region Salesperson  Units Sold  Unit Price  \
15  2025-08-20      Laptop  South         Bob         NaN       900.0   
16  2025-08-25  Smartphone   West     Charlie         7.0         NaN   
17  2025-09-01      Tablet   East       Diana         1.0       310.0   
18  2025-09-10     Monitor  North       Ethan         2.0       215.0   
19  2025-09-15  Headphones  South       Alice         5.0       100.0   

    Total Sales  
15          NaN  
16       3850.0  
17        310.0  
18        430.0  
19        500.0  


In [54]:
print(df1.isnull())

     Date  Product  Region  Salesperson  Units Sold  Unit Price  Total Sales
0   False    False   False        False       False       False        False
1   False    False   False        False       False       False        False
2   False    False    True        False       False       False        False
3   False    False   False         True       False       False        False
4   False    False   False        False        True       False         True
5   False    False   False        False       False       False        False
6   False    False   False        False       False        True        False
7   False    False   False        False       False       False        False
8   False     True   False        False       False       False        False
9   False    False   False        False       False       False        False
10  False    False    True        False       False       False        False
11  False    False   False        False       False       False         True

In [56]:
df1.isnull().any()

Date           False
Product         True
Region          True
Salesperson     True
Units Sold      True
Unit Price      True
Total Sales     True
dtype: bool

In [58]:
df1.isnull().any(axis=1)

0     False
1     False
2      True
3      True
4      True
5     False
6      True
7     False
8      True
9     False
10     True
11     True
12     True
13    False
14    False
15     True
16     True
17    False
18    False
19    False
dtype: bool

In [57]:
df1.isnull().sum()

Date           0
Product        1
Region         2
Salesperson    2
Units Sold     2
Unit Price     2
Total Sales    3
dtype: int64

In [61]:
df1_filled = df1.fillna(0)

In [62]:
df1_filled

Date     Product Region Salesperson  Units Sold  Unit Price  \
0   2025-01-05      Laptop  North       Alice         3.0       750.0   
1   2025-01-10  Smartphone  South         Bob         5.0       500.0   
2   2025-02-02      Tablet      0     Charlie         2.0       300.0   
3   2025-02-14     Monitor   West           0         4.0       200.0   
4   2025-03-01  Headphones  North       Ethan         0.0       100.0   
5   2025-03-18      Laptop   East       Alice         1.0       800.0   
6   2025-04-04  Smartphone   West         Bob         6.0         0.0   
7   2025-04-20      Tablet  South     Charlie         3.0       280.0   
8   2025-05-09           0  North       Diana         2.0       220.0   
9   2025-06-15  Headphones   East       Ethan         7.0        90.0   
10  2025-07-01      Laptop      0       Alice         2.0       850.0   
11  2025-07-10  Smartphone   West         Bob         5.0       510.0   
12  2025-07-25      Tablet  South           0         4.0       295.0   
13  2025-08-02     Monitor  North       Ethan         3.0       210.0   
14  2025-08-12  Headphones   East       Alice         6.0        95.0   
15  2025-08-20      Laptop  South         Bob         0.0       900.0   
16  2025-08-25  Smartphone   West     Charlie         7.0         0.0   
17  2025-09-01      Tablet   East       Diana         1.0       310.0   
18  2025-09-10     Monitor  North       Ethan         2.0       215.0   
19  2025-09-15  Headphones  South       Alice         5.0       100.0   

    Total Sales  
0        2250.0  
1        2500.0  
2         600.0  
3         800.0  
4           0.0  
5         800.0  
6        3300.0  
7         840.0  
8         440.0  
9         630.0  
10       1700.0  
11          0.0  
12       1180.0  
13        630.0  
14        570.0  
15          0.0  
16       3850.0  
17        310.0  
18        430.0  
19        500.0

In [64]:
df1['units sold filled'] = df1['Units Sold'].fillna(df1['Units Sold'].mean())

In [65]:
df1

Date     Product Region Salesperson  Units Sold  Unit Price  \
0   2025-01-05      Laptop  North       Alice         3.0       750.0   
1   2025-01-10  Smartphone  South         Bob         5.0       500.0   
2   2025-02-02      Tablet    NaN     Charlie         2.0       300.0   
3   2025-02-14     Monitor   West         NaN         4.0       200.0   
4   2025-03-01  Headphones  North       Ethan         NaN       100.0   
5   2025-03-18      Laptop   East       Alice         1.0       800.0   
6   2025-04-04  Smartphone   West         Bob         6.0         NaN   
7   2025-04-20      Tablet  South     Charlie         3.0       280.0   
8   2025-05-09         NaN  North       Diana         2.0       220.0   
9   2025-06-15  Headphones   East       Ethan         7.0        90.0   
10  2025-07-01      Laptop    NaN       Alice         2.0       850.0   
11  2025-07-10  Smartphone   West         Bob         5.0       510.0   
12  2025-07-25      Tablet  South         NaN         4.0       295.0   
13  2025-08-02     Monitor  North       Ethan         3.0       210.0   
14  2025-08-12  Headphones   East       Alice         6.0        95.0   
15  2025-08-20      Laptop  South         Bob         NaN       900.0   
16  2025-08-25  Smartphone   West     Charlie         7.0         NaN   
17  2025-09-01      Tablet   East       Diana         1.0       310.0   
18  2025-09-10     Monitor  North       Ethan         2.0       215.0   
19  2025-09-15  Headphones  South       Alice         5.0       100.0   

    Total Sales  units sold filled  
0        2250.0           3.000000  
1        2500.0           5.000000  
2         600.0           2.000000  
3         800.0           4.000000  
4           NaN           3.777778  
5         800.0           1.000000  
6        3300.0           6.000000  
7         840.0           3.000000  
8         440.0           2.000000  
9         630.0           7.000000  
10       1700.0           2.000000  
11          NaN           5.000000  
12       1180.0           4.000000  
13        630.0           3.000000  
14        570.0           6.000000  
15          NaN           3.777778  
16       3850.0           7.000000  
17        310.0           1.000000  
18        430.0           2.000000  
19        500.0           5.000000